version: '3.8'
services:
  train:
    build:
      context: ./
      dockerfile: Dockerfile.train
    volumes:
      - ./model:/workspace/model
      - ./data:/workspace/data
    restart: on-failure
    command: bash -c "make run-training"
    # command: python train.py add cli args here as to where the model is supposed to be stored

  evaluate:
    build:
      context: ./
      dockerfile: Dockerfile.eval

    #Mount volumes
    volumes:
      - ./data:/workspace/data
      - ./model:/workspace/model
    command: python eval.py
    #also mount the mnist volume

    # Run the evaluation command
    # command: python eval.py maybe add command line argument here, like where the model is located

  # infer:
  #   # Build the inference service
  #   # ...

  #   # Mount volumes
  #   # ...

  #   # Run the inference command
  #   # command: python infer.py
